<?php

use Drupal\node\NodeInterface;
use Drupal\drupaltest\Event\CustomNodeEvent;
use Drupal\views\ViewExecutable;

function drupaltest_node_insert(NodeInterface $node){
	$event = new CustomNodeEvent($node);
    \Drupal::service('event_dispatcher')->dispatch($event, CustomNodeEvent::NODEADD_EVENT);
}

function drupaltest_node_update(NodeInterface $node){
	$event = new CustomNodeEvent($node);
    \Drupal::service('event_dispatcher')->dispatch($event, CustomNodeEvent::NODEUPDATE_EVENT);
}

function drupaltest_theme(){
	return [
      'marquee' => [
      	'variables' => [
      	   'content' => '',
      	   'attributes' => [],
      	],
      ],
      'progress' => [
      	'variables' => [
      	   'content' => '',
      	   'attributes' => [],
      	],
      ],
      'node_modal' => [
        'variables' => [
           'nid' => '',
        ],
      ],
    ];
}

function drupaltest_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'super_awesome_view')) {
    $view->element['#attached']['library'][] = 'custom/custom_view';
  }
}