id: d6_ip2country_settings
label: Ip2Country configuration settings
migration_tags:
  - Drupal 6
  - Configuration

source:
  plugin: variable
  source_module: ip2country
  variables:
    - ip2country_debug
    - ip2country_test_type
    - ip2country_test_ip_address
    - ip2country_test_country
    - ip2country_rir
    - ip2country_update_interval
    - ip2country_watchdog

process:
  debug: ip2country_debug
  test_type: ip2country_test_type
  test_ip_address: ip2country_test_ip_address
  test_country: ip2country_test_country
  rir: ip2country_rir
  update_interval: ip2country_update_interval
  watchdog: ip2country_watchdog

destination:
  plugin: config
  config_name: ip2country.settings
