id: d7_ip2country_settings
label: Ip2Country configuration settings
migration_tags:
  - Drupal 7
  - Configuration

source:
  plugin: variable
  source_module: ip2country
  variables:
    - ip2country_debug
    - ip2country_test_type
    - ip2country_test_ip_address
    - ip2country_test_country
    - ip2country_rir
    - ip2country_md5_checksum
    - ip2country_update_interval
    - ip2country_update_batch_size
    - ip2country_watchdog

process:
  debug: ip2country_debug
  test_type: ip2country_test_type
  test_ip_address: ip2country_test_ip_address
  test_country: ip2country_test_country
  rir: ip2country_rir
  md5_checksum: ip2country_md5_checksum
  update_interval: ip2country_update_interval
  batch_size: ip2country_update_batch_size
  watchdog: ip2country_watchdog

destination:
  plugin: config
  config_name: ip2country.settings
