<?php

/**
 * @file
 * Install, update, and uninstall functions for the behat_ui module.
 */

/**
 * Implements hook_install().
 */
function behat_ui_install() {
  $install_message = t("Automated tests using Behat/Mink, Run tests, and create tests under Administration -> Configuration -> Development -> Behat UI");
  \Drupal::logger('behat_ui')->notice($install_message);
  \Drupal::messenger()->addWarning($install_message);
}
